# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source "https://github.com/CocoaPods/Specs"
source 'https://github.com/aliyun/aliyun-specs.git'

use_frameworks!
## workspace文件名
workspace 'CIMSDK.xcworkspace'

# 工作模块 Flutter Add-to-App 依赖；必须先在 work_module 执行 flutter pub get。
work_module_path = File.join(__dir__, 'work_module')
load File.join(work_module_path, '.ios', 'Flutter', 'podhelper.rb')

## 主工程路径
##project './CIMKit/CIMKit.xcodeproj'

## 工程路径
target 'CandyTalkPro' do
project './NoaChatSDKCore/CandyTalkPro.xcodeproj'

  pod "AFNetworking", '4.0.1'
  pod 'MJExtension', '3.4.0'
  pod 'SocketRocket', '0.6.0'
  pod 'MMKV', '1.2.16'
  pod 'NullSafe', '2.0'
  pod 'Protobuf', '3.21.5'
  #新的架构实现SDK
  pod 'CocoaAsyncSocket', '7.6.5'
  pod 'SAMKeychain', '1.5.3'
  
  #音视频要求iOS13最低(SwiftUI)
  pod 'LiveKitClient', '1.0.8'

  #即构音视频
  pod 'ZegoExpressEngine', '3.5.0'

  
  # RAC
  pod 'ReactiveObjC', :inhibit_warnings => true
  
  # 网络监听
  pod 'NetworkStatus', :path => './NetWorkStatus/NetWorkStatus.podspec'
  
end

target 'CandyTalk' do
project './NoaChatKit/CandyTalk.xcodeproj'

  # 仅 CandyTalk 宿主嵌入工作模块，CandyTalkPro 服务工程保持不变。
  install_all_flutter_pods(work_module_path)

  pod "AFNetworking", '4.0.1'
  pod 'MJExtension', '3.4.0'
  pod 'SocketRocket', '0.6.0'
  pod 'MMKV', '1.2.16'
  pod 'NullSafe', '2.0'
  pod 'Protobuf', '3.21.5'
  #新的架构实现SDK
  pod 'CocoaAsyncSocket', '7.6.5'
  
  
  pod 'MJRefresh', '3.7.5'
  
  pod 'MBProgressHUD', '1.2.0'
  
  pod 'IQKeyboardManager'
  
  pod 'Masonry', '1.1.0'
  
  pod 'SAMKeychain', '1.5.3'
  
  pod 'SDWebImage', '5.20.0'
  #SVG图片格式
  pod 'SDWebImageSVGCoder', '1.6.1'
  #WebP图片格式(libwebp 1.2.4)
  pod 'SDWebImageWebPCoder', '0.9.1'
  pod 'SDWebImageFLPlugin'
  #空态界面展示
  pod 'DZNEmptyDataSet', '1.8.1'
  
 
  #超级播放器(最新版是收费的)
  pod 'TXLiteAVSDK_Player', '7.6.9355'
  
  #用此网络请求，封装了一个文件下载工具 ZCacheManager
  pod 'ASIHTTPRequest', '1.8.2'

  pod 'FMDB', '2.7.5'
  
  #界面嵌套
  pod 'JXCategoryView', '1.6.1'
  
  #音视频要求iOS13最低(SwiftUI)
  pod 'LiveKitClient', '1.0.8'

  #即构音视频
  pod 'ZegoExpressEngine', '3.5.0'
  
  #防止崩溃
  pod 'AvoidCrash', '2.5.2'
  

  pod 'SDCycleScrollView'
  pod 'Toast', '~> 4.1.1'
  pod 'TTTAttributedLabel', '2.0.0'

  #阿里云OSS
  pod 'AliyunOSSiOS'

  #aliyun云解析DNS
  pod 'AlicloudPDNS', '2.1.9'

  #亚马逊云存储 AWS S3
  pod 'AWSS3'
  
  #腾讯云存储
  pod 'QCloudCOSXML', '6.4.8'

  #swift
  #SnapKit
  pod 'SnapKit', '5.6.0'
  #图片下载
  pod 'Kingfisher'
  #openinstall数据统计
  pod 'libOpenInstallSDK'

  # RAC
  pod 'ReactiveObjC', :inhibit_warnings => true
  
  # 网络监听
  pod 'NetworkStatus', :path => './NetWorkStatus/NetWorkStatus.podspec'
  
  # 加解密
  pod 'EncryptLib', :path => './EncryptLib/EncryptLib.podspec'

  # 主题配置
  pod 'TKThemeConfig', :path => './TKThemeConfig/TKThemeConfig.podspec'
  
  # GaOnchain 请求组件
  pod 'GaOnchainLib', :path => './GaOnchainLib/GaOnchainLib.podspec'
  

    
  pod "FSPlayer", :podspec => 'https://github.com/debugly/fsplayer/releases/download/1.0.2/FSPlayer.spec.json'
  
end

post_install do |installer|
  # 应用 Flutter 引擎和插件要求的 iOS 构建设置。
  flutter_post_install(installer)

  # Reachability 3.7.6 与 QCloudTrack 6.4.8 引用了 Xcode 26 禁止模块外访问的 netinet6 私有头文件。
  # 两个 Pod 均未使用此头文件中的声明，移除引用后继续使用公开的 netinet/in.h。
  private_header_sources = [
    File.join(installer.sandbox.root.to_s, 'Reachability', 'Reachability.m'),
    File.join(installer.sandbox.root.to_s, 'QCloudTrack', 'QCloudTrack', 'Classes', 'Default', 'Utils', 'QCloudTrackNetworkUtils.m')
  ]
  private_header_sources.each do |source_path|
    next unless File.exist?(source_path)

    source = File.read(source_path)
    private_header_import = "#import <netinet6/in6.h>\n"
    if source.include?(private_header_import)
      # CocoaPods 缓存恢复的源码可能是只读文件，仅为当前生成副本补充 owner-write 权限。
      File.chmod(File.stat(source_path).mode | 0o200, source_path)
      File.write(source_path, source.sub(private_header_import, ''))
    end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      # 部分 Pod（如 CocoaLumberjack）会声明 Swift 6.x，旧版 Xcode 只支持到 5.0
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
       target.build_configurations.each do |config|
         config.build_settings['CODE_SIGN_IDENTITY'] = ''
         config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
       end
    end
  end
end

post_integrate do |installer|
  # 客户工程集成完成后再校正脚本；更早的 post_install 会被 CocoaPods随后的集成步骤覆盖。
  installer.aggregate_targets
    .select { |aggregate_target| aggregate_target.name == 'Pods-CandyTalk' }
    .flat_map(&:user_targets)
    .flat_map(&:shell_script_build_phases)
    .select { |phase| phase.name&.include?('Flutter Build work_module Script') }
    .each do |phase|
      phase.shell_script = phase.shell_script.gsub(
        '${SRCROOT}/work_module/',
        '${SRCROOT}/../work_module/'
      )
      phase.project.save
    end
end
# com.codeappyang.idnumberft
