// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Nav.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import <stdatomic.h>

#import "Nav.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wdirect-ivar-access"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#pragma mark - Objective C Class declarations
// Forward declarations of Objective C classes that we can use as
// static values in struct initializers.
// We don't use [Foo class] because it is not a static value.
GPBObjCClassDeclaration(Auth);
GPBObjCClassDeclaration(AuthAck);
GPBObjCClassDeclaration(FallbackEndpoints);
GPBObjCClassDeclaration(IMServerEndpoint);
GPBObjCClassDeclaration(IMServerListRequest);
GPBObjCClassDeclaration(IMServerListResponse);
GPBObjCClassDeclaration(NavData);
GPBObjCClassDeclaration(NavigationConfig);
GPBObjCClassDeclaration(NavigationMeta);

#pragma mark - NavRoot

@implementation NavRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - NavRoot_FileDescriptor

static GPBFileDescriptor *NavRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - NavMessage

@implementation NavMessage

@dynamic dataBodyOneOfCase;
@dynamic dataType;
@dynamic auth;
@dynamic authAck;
@dynamic imServerListRequest;
@dynamic imServerListResponse;

typedef struct NavMessage__storage_ {
  uint32_t _has_storage_[2];
  NavMessage_DataType dataType;
  Auth *auth;
  AuthAck *authAck;
  IMServerListRequest *imServerListRequest;
  IMServerListResponse *imServerListResponse;
} NavMessage__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "dataType",
        .dataTypeSpecific.enumDescFunc = NavMessage_DataType_EnumDescriptor,
        .number = NavMessage_FieldNumber_DataType,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NavMessage__storage_, dataType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "auth",
        .dataTypeSpecific.clazz = GPBObjCClass(Auth),
        .number = NavMessage_FieldNumber_Auth,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(NavMessage__storage_, auth),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "authAck",
        .dataTypeSpecific.clazz = GPBObjCClass(AuthAck),
        .number = NavMessage_FieldNumber_AuthAck,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(NavMessage__storage_, authAck),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "imServerListRequest",
        .dataTypeSpecific.clazz = GPBObjCClass(IMServerListRequest),
        .number = NavMessage_FieldNumber_ImServerListRequest,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(NavMessage__storage_, imServerListRequest),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "imServerListResponse",
        .dataTypeSpecific.clazz = GPBObjCClass(IMServerListResponse),
        .number = NavMessage_FieldNumber_ImServerListResponse,
        .hasIndex = -1,
        .offset = (uint32_t)offsetof(NavMessage__storage_, imServerListResponse),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NavMessage class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NavMessage__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    static const char *oneofs[] = {
      "dataBody",
    };
    [localDescriptor setupOneofs:oneofs
                           count:(uint32_t)(sizeof(oneofs) / sizeof(char*))
                   firstHasIndex:-1];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\003\003\007\000\004\023\000\005\024\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t NavMessage_DataType_RawValue(NavMessage *message) {
  GPBDescriptor *descriptor = [NavMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:NavMessage_FieldNumber_DataType];
  return GPBGetMessageRawEnumField(message, field);
}

void SetNavMessage_DataType_RawValue(NavMessage *message, int32_t value) {
  GPBDescriptor *descriptor = [NavMessage descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:NavMessage_FieldNumber_DataType];
  GPBSetMessageRawEnumField(message, field, value);
}

void NavMessage_ClearDataBodyOneOfCase(NavMessage *message) {
  GPBDescriptor *descriptor = [NavMessage descriptor];
  GPBOneofDescriptor *oneof = [descriptor.oneofs objectAtIndex:0];
  GPBClearOneof(message, oneof);
}
#pragma mark - Enum NavMessage_DataType

GPBEnumDescriptor *NavMessage_DataType_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "NavAuth\000NavAuthAck\000ImServerListReq\000ImSer"
        "verListResp\000";
    static const int32_t values[] = {
        NavMessage_DataType_NavAuth,
        NavMessage_DataType_NavAuthAck,
        NavMessage_DataType_ImServerListReq,
        NavMessage_DataType_ImServerListResp,
    };
    static const char *extraTextFormatInfo = "\004\000\'\000\001*\000\002/\000\0030\000";
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(NavMessage_DataType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:NavMessage_DataType_IsValidValue
                              extraTextFormatInfo:extraTextFormatInfo];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL NavMessage_DataType_IsValidValue(int32_t value__) {
  switch (value__) {
    case NavMessage_DataType_NavAuth:
    case NavMessage_DataType_NavAuthAck:
    case NavMessage_DataType_ImServerListReq:
    case NavMessage_DataType_ImServerListResp:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - Auth

@implementation Auth

@dynamic appkey;
@dynamic timestamp;
@dynamic sn;
@dynamic nonce;
@dynamic appType;
@dynamic sign;

typedef struct Auth__storage_ {
  uint32_t _has_storage_[1];
  int32_t appType;
  NSString *appkey;
  NSString *sn;
  NSString *nonce;
  NSString *sign;
  int64_t timestamp;
} Auth__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "appkey",
        .dataTypeSpecific.clazz = Nil,
        .number = Auth_FieldNumber_Appkey,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(Auth__storage_, appkey),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "timestamp",
        .dataTypeSpecific.clazz = Nil,
        .number = Auth_FieldNumber_Timestamp,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(Auth__storage_, timestamp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "sn",
        .dataTypeSpecific.clazz = Nil,
        .number = Auth_FieldNumber_Sn,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(Auth__storage_, sn),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "nonce",
        .dataTypeSpecific.clazz = Nil,
        .number = Auth_FieldNumber_Nonce,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(Auth__storage_, nonce),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appType",
        .dataTypeSpecific.clazz = Nil,
        .number = Auth_FieldNumber_AppType,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(Auth__storage_, appType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "sign",
        .dataTypeSpecific.clazz = Nil,
        .number = Auth_FieldNumber_Sign,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(Auth__storage_, sign),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[Auth class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(Auth__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\005\007\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - AuthAck

@implementation AuthAck

@dynamic code;
@dynamic message;
@dynamic hasData_p, data_p;

typedef struct AuthAck__storage_ {
  uint32_t _has_storage_[1];
  NSString *message;
  NavData *data_p;
  int64_t code;
} AuthAck__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "code",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthAck_FieldNumber_Code,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(AuthAck__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "message",
        .dataTypeSpecific.clazz = Nil,
        .number = AuthAck_FieldNumber_Message,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(AuthAck__storage_, message),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "data_p",
        .dataTypeSpecific.clazz = GPBObjCClass(NavData),
        .number = AuthAck_FieldNumber_Data_p,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(AuthAck__storage_, data_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[AuthAck class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(AuthAck__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - NavData

@implementation NavData

@dynamic navEncryptStr;

typedef struct NavData__storage_ {
  uint32_t _has_storage_[1];
  NSString *navEncryptStr;
} NavData__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "navEncryptStr",
        .dataTypeSpecific.clazz = Nil,
        .number = NavData_FieldNumber_NavEncryptStr,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NavData__storage_, navEncryptStr),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NavData class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NavData__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\r\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - IMServerListRequest

@implementation IMServerListRequest

@dynamic appId;
@dynamic appType;
@dynamic clientVersion;
@dynamic region;
@dynamic deviceType;
@dynamic timestamp;
@dynamic signature;
@dynamic clientIp;
@dynamic sdkVersion;
@dynamic nonce;

typedef struct IMServerListRequest__storage_ {
  uint32_t _has_storage_[1];
  IMServerListRequest_DataType appType;
  NSString *appId;
  NSString *clientVersion;
  NSString *region;
  NSString *deviceType;
  NSString *signature;
  NSString *clientIp;
  NSString *sdkVersion;
  NSString *nonce;
  int64_t timestamp;
} IMServerListRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "appId",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListRequest_FieldNumber_AppId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMServerListRequest__storage_, appId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "appType",
        .dataTypeSpecific.enumDescFunc = IMServerListRequest_DataType_EnumDescriptor,
        .number = IMServerListRequest_FieldNumber_AppType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMServerListRequest__storage_, appType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "clientVersion",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListRequest_FieldNumber_ClientVersion,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMServerListRequest__storage_, clientVersion),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "region",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListRequest_FieldNumber_Region,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(IMServerListRequest__storage_, region),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "deviceType",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListRequest_FieldNumber_DeviceType,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(IMServerListRequest__storage_, deviceType),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "timestamp",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListRequest_FieldNumber_Timestamp,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(IMServerListRequest__storage_, timestamp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "signature",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListRequest_FieldNumber_Signature,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(IMServerListRequest__storage_, signature),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "clientIp",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListRequest_FieldNumber_ClientIp,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(IMServerListRequest__storage_, clientIp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "sdkVersion",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListRequest_FieldNumber_SdkVersion,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(IMServerListRequest__storage_, sdkVersion),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "nonce",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListRequest_FieldNumber_Nonce,
        .hasIndex = 9,
        .offset = (uint32_t)offsetof(IMServerListRequest__storage_, nonce),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMServerListRequest class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMServerListRequest__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\002\007\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t IMServerListRequest_AppType_RawValue(IMServerListRequest *message) {
  GPBDescriptor *descriptor = [IMServerListRequest descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMServerListRequest_FieldNumber_AppType];
  return GPBGetMessageRawEnumField(message, field);
}

void SetIMServerListRequest_AppType_RawValue(IMServerListRequest *message, int32_t value) {
  GPBDescriptor *descriptor = [IMServerListRequest descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:IMServerListRequest_FieldNumber_AppType];
  GPBSetMessageRawEnumField(message, field, value);
}

#pragma mark - Enum IMServerListRequest_DataType

GPBEnumDescriptor *IMServerListRequest_DataType_EnumDescriptor(void) {
  static _Atomic(GPBEnumDescriptor*) descriptor = nil;
  if (!descriptor) {
    static const char *valueNames =
        "Common\000Independent\000";
    static const int32_t values[] = {
        IMServerListRequest_DataType_Common,
        IMServerListRequest_DataType_Independent,
    };
    GPBEnumDescriptor *worker =
        [GPBEnumDescriptor allocDescriptorForName:GPBNSStringifySymbol(IMServerListRequest_DataType)
                                       valueNames:valueNames
                                           values:values
                                            count:(uint32_t)(sizeof(values) / sizeof(int32_t))
                                     enumVerifier:IMServerListRequest_DataType_IsValidValue];
    GPBEnumDescriptor *expected = nil;
    if (!atomic_compare_exchange_strong(&descriptor, &expected, worker)) {
      [worker release];
    }
  }
  return descriptor;
}

BOOL IMServerListRequest_DataType_IsValidValue(int32_t value__) {
  switch (value__) {
    case IMServerListRequest_DataType_Common:
    case IMServerListRequest_DataType_Independent:
      return YES;
    default:
      return NO;
  }
}

#pragma mark - IMServerListResponse

@implementation IMServerListResponse

@dynamic statusCode;
@dynamic message;
@dynamic responseBody;
@dynamic serverTimestamp;

typedef struct IMServerListResponse__storage_ {
  uint32_t _has_storage_[1];
  int32_t statusCode;
  NSString *message;
  NSData *responseBody;
  int64_t serverTimestamp;
} IMServerListResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "statusCode",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListResponse_FieldNumber_StatusCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMServerListResponse__storage_, statusCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "message",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListResponse_FieldNumber_Message,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMServerListResponse__storage_, message),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "responseBody",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListResponse_FieldNumber_ResponseBody,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMServerListResponse__storage_, responseBody),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBytes,
      },
      {
        .name = "serverTimestamp",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListResponse_FieldNumber_ServerTimestamp,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(IMServerListResponse__storage_, serverTimestamp),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMServerListResponse class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMServerListResponse__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - IMServerListResponseBody

@implementation IMServerListResponseBody

@dynamic imEndpointsArray, imEndpointsArray_Count;
@dynamic hasMeta, meta;
@dynamic hasFallbackEndpoints, fallbackEndpoints;
@dynamic cacheTtl;

typedef struct IMServerListResponseBody__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *imEndpointsArray;
  NavigationMeta *meta;
  FallbackEndpoints *fallbackEndpoints;
  int64_t cacheTtl;
} IMServerListResponseBody__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "imEndpointsArray",
        .dataTypeSpecific.clazz = GPBObjCClass(IMServerEndpoint),
        .number = IMServerListResponseBody_FieldNumber_ImEndpointsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(IMServerListResponseBody__storage_, imEndpointsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "meta",
        .dataTypeSpecific.clazz = GPBObjCClass(NavigationMeta),
        .number = IMServerListResponseBody_FieldNumber_Meta,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMServerListResponseBody__storage_, meta),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "fallbackEndpoints",
        .dataTypeSpecific.clazz = GPBObjCClass(FallbackEndpoints),
        .number = IMServerListResponseBody_FieldNumber_FallbackEndpoints,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMServerListResponseBody__storage_, fallbackEndpoints),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "cacheTtl",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerListResponseBody_FieldNumber_CacheTtl,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMServerListResponseBody__storage_, cacheTtl),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMServerListResponseBody class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMServerListResponseBody__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - IMServerEndpoint

@implementation IMServerEndpoint

@dynamic ip;
@dynamic port;
@dynamic weight;
@dynamic region;
@dynamic status;
@dynamic latency;
@dynamic serverId;
@dynamic clusterId;
@dynamic load;
@dynamic protocolsArray, protocolsArray_Count;

typedef struct IMServerEndpoint__storage_ {
  uint32_t _has_storage_[1];
  int32_t port;
  int32_t weight;
  int32_t load;
  NSString *ip;
  NSString *region;
  NSString *status;
  NSString *serverId;
  NSString *clusterId;
  NSMutableArray *protocolsArray;
  int64_t latency;
} IMServerEndpoint__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "ip",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerEndpoint_FieldNumber_Ip,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(IMServerEndpoint__storage_, ip),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "port",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerEndpoint_FieldNumber_Port,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(IMServerEndpoint__storage_, port),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "weight",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerEndpoint_FieldNumber_Weight,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(IMServerEndpoint__storage_, weight),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "region",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerEndpoint_FieldNumber_Region,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(IMServerEndpoint__storage_, region),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "status",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerEndpoint_FieldNumber_Status,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(IMServerEndpoint__storage_, status),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "latency",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerEndpoint_FieldNumber_Latency,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(IMServerEndpoint__storage_, latency),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "serverId",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerEndpoint_FieldNumber_ServerId,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(IMServerEndpoint__storage_, serverId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "clusterId",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerEndpoint_FieldNumber_ClusterId,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(IMServerEndpoint__storage_, clusterId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "load",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerEndpoint_FieldNumber_Load,
        .hasIndex = 8,
        .offset = (uint32_t)offsetof(IMServerEndpoint__storage_, load),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "protocolsArray",
        .dataTypeSpecific.clazz = Nil,
        .number = IMServerEndpoint_FieldNumber_ProtocolsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(IMServerEndpoint__storage_, protocolsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[IMServerEndpoint class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(IMServerEndpoint__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - NavigationMeta

@implementation NavigationMeta

@dynamic navVersion;
@dynamic hasConfig, config;
@dynamic nextUpdateTime;
@dynamic traceId;

typedef struct NavigationMeta__storage_ {
  uint32_t _has_storage_[1];
  NSString *navVersion;
  NavigationConfig *config;
  NSString *traceId;
  int64_t nextUpdateTime;
} NavigationMeta__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "navVersion",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationMeta_FieldNumber_NavVersion,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NavigationMeta__storage_, navVersion),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "config",
        .dataTypeSpecific.clazz = GPBObjCClass(NavigationConfig),
        .number = NavigationMeta_FieldNumber_Config,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(NavigationMeta__storage_, config),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "nextUpdateTime",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationMeta_FieldNumber_NextUpdateTime,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(NavigationMeta__storage_, nextUpdateTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "traceId",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationMeta_FieldNumber_TraceId,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(NavigationMeta__storage_, traceId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NavigationMeta class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NavigationMeta__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - NavigationConfig

@implementation NavigationConfig

@dynamic connectTimeout;
@dynamic readTimeout;
@dynamic maxRetryCount;
@dynamic raceTimeout;
@dynamic cacheDuration;
@dynamic enableNetworkDetect;
@dynamic sentryUrlsArray, sentryUrlsArray_Count;
@dynamic loganUrlsArray, loganUrlsArray_Count;

typedef struct NavigationConfig__storage_ {
  uint32_t _has_storage_[1];
  int32_t connectTimeout;
  int32_t readTimeout;
  int32_t maxRetryCount;
  int32_t raceTimeout;
  int32_t cacheDuration;
  NSMutableArray *sentryUrlsArray;
  NSMutableArray *loganUrlsArray;
} NavigationConfig__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "connectTimeout",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationConfig_FieldNumber_ConnectTimeout,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NavigationConfig__storage_, connectTimeout),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "readTimeout",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationConfig_FieldNumber_ReadTimeout,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(NavigationConfig__storage_, readTimeout),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "maxRetryCount",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationConfig_FieldNumber_MaxRetryCount,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(NavigationConfig__storage_, maxRetryCount),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "raceTimeout",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationConfig_FieldNumber_RaceTimeout,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(NavigationConfig__storage_, raceTimeout),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "cacheDuration",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationConfig_FieldNumber_CacheDuration,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(NavigationConfig__storage_, cacheDuration),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "enableNetworkDetect",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationConfig_FieldNumber_EnableNetworkDetect,
        .hasIndex = 5,
        .offset = 6,  // Stored in _has_storage_ to save space.
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "sentryUrlsArray",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationConfig_FieldNumber_SentryUrlsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(NavigationConfig__storage_, sentryUrlsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "loganUrlsArray",
        .dataTypeSpecific.clazz = Nil,
        .number = NavigationConfig_FieldNumber_LoganUrlsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(NavigationConfig__storage_, loganUrlsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NavigationConfig class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NavigationConfig__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - FallbackEndpoints

@implementation FallbackEndpoints

@dynamic domesticArray, domesticArray_Count;
@dynamic overseasArray, overseasArray_Count;

typedef struct FallbackEndpoints__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *domesticArray;
  NSMutableArray *overseasArray;
} FallbackEndpoints__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "domesticArray",
        .dataTypeSpecific.clazz = Nil,
        .number = FallbackEndpoints_FieldNumber_DomesticArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(FallbackEndpoints__storage_, domesticArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "overseasArray",
        .dataTypeSpecific.clazz = Nil,
        .number = FallbackEndpoints_FieldNumber_OverseasArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(FallbackEndpoints__storage_, overseasArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[FallbackEndpoints class]
                                     rootClass:[NavRoot class]
                                          file:NavRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(FallbackEndpoints__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
