// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Nav.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Auth;
@class AuthAck;
@class FallbackEndpoints;
@class IMServerEndpoint;
@class IMServerListRequest;
@class IMServerListResponse;
@class NavData;
@class NavigationConfig;
@class NavigationMeta;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum NavMessage_DataType

typedef GPB_ENUM(NavMessage_DataType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  NavMessage_DataType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 认证消息 */
  NavMessage_DataType_NavAuth = 0,

  /** 认证回执消息 */
  NavMessage_DataType_NavAuthAck = 1,

  /** IM服务器列表请求 */
  NavMessage_DataType_ImServerListReq = 2,

  /** IM服务器列表响应 */
  NavMessage_DataType_ImServerListResp = 3,
};

GPBEnumDescriptor *NavMessage_DataType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL NavMessage_DataType_IsValidValue(int32_t value);

#pragma mark - Enum IMServerListRequest_DataType

typedef GPB_ENUM(IMServerListRequest_DataType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  IMServerListRequest_DataType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** 公共打包 */
  IMServerListRequest_DataType_Common = 0,

  /** 独立打包 */
  IMServerListRequest_DataType_Independent = 1,
};

GPBEnumDescriptor *IMServerListRequest_DataType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL IMServerListRequest_DataType_IsValidValue(int32_t value);

#pragma mark - NavRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface NavRoot : GPBRootObject
@end

#pragma mark - NavMessage

typedef GPB_ENUM(NavMessage_FieldNumber) {
  NavMessage_FieldNumber_DataType = 1,
  NavMessage_FieldNumber_Auth = 2,
  NavMessage_FieldNumber_AuthAck = 3,
  NavMessage_FieldNumber_ImServerListRequest = 4,
  NavMessage_FieldNumber_ImServerListResponse = 5,
};

typedef GPB_ENUM(NavMessage_DataBody_OneOfCase) {
  NavMessage_DataBody_OneOfCase_GPBUnsetOneOfCase = 0,
  NavMessage_DataBody_OneOfCase_Auth = 2,
  NavMessage_DataBody_OneOfCase_AuthAck = 3,
  NavMessage_DataBody_OneOfCase_ImServerListRequest = 4,
  NavMessage_DataBody_OneOfCase_ImServerListResponse = 5,
};

GPB_FINAL @interface NavMessage : GPBMessage

/** 消息类型 */
@property(nonatomic, readwrite) NavMessage_DataType dataType;

/** oneof表示多个当中有一个被赋值 */
@property(nonatomic, readonly) NavMessage_DataBody_OneOfCase dataBodyOneOfCase;

/** 下面类型同一时刻只能出现一个 */
@property(nonatomic, readwrite, strong, null_resettable) Auth *auth;

@property(nonatomic, readwrite, strong, null_resettable) AuthAck *authAck;

@property(nonatomic, readwrite, strong, null_resettable) IMServerListRequest *imServerListRequest;

@property(nonatomic, readwrite, strong, null_resettable) IMServerListResponse *imServerListResponse;

@end

/**
 * Fetches the raw value of a @c NavMessage's @c dataType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t NavMessage_DataType_RawValue(NavMessage *message);
/**
 * Sets the raw value of an @c NavMessage's @c dataType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetNavMessage_DataType_RawValue(NavMessage *message, int32_t value);

/**
 * Clears whatever value was set for the oneof 'dataBody'.
 **/
void NavMessage_ClearDataBodyOneOfCase(NavMessage *message);

#pragma mark - Auth

typedef GPB_ENUM(Auth_FieldNumber) {
  Auth_FieldNumber_Appkey = 1,
  Auth_FieldNumber_Timestamp = 2,
  Auth_FieldNumber_Sn = 3,
  Auth_FieldNumber_Nonce = 4,
  Auth_FieldNumber_AppType = 5,
  Auth_FieldNumber_Sign = 6,
};

GPB_FINAL @interface Auth : GPBMessage

/** 邀请码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appkey;

/** 13位UTC时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

/** 设备sn码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sn;

/** 随机字符串 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nonce;

/** app类型 0:公共打包 1:独立打包 */
@property(nonatomic, readwrite) int32_t appType;

/** appkey+timestamp+sn+nonce+appType AES加密 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sign;

@end

#pragma mark - AuthAck

typedef GPB_ENUM(AuthAck_FieldNumber) {
  AuthAck_FieldNumber_Code = 1,
  AuthAck_FieldNumber_Message = 2,
  AuthAck_FieldNumber_Data_p = 3,
};

GPB_FINAL @interface AuthAck : GPBMessage

/** 状态码 200 成功 401 邀请码不存在 402 解密失败 403 IP被封禁 404 设备被封禁 501 服务端异常 */
@property(nonatomic, readwrite) int64_t code;

/** 消息内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** 导航数据 */
@property(nonatomic, readwrite, strong, null_resettable) NavData *data_p;
/** Test to see if @c data_p has been set. */
@property(nonatomic, readwrite) BOOL hasData_p;

@end

#pragma mark - NavData

typedef GPB_ENUM(NavData_FieldNumber) {
  NavData_FieldNumber_NavEncryptStr = 1,
};

/**
 * 导航数据
 **/
GPB_FINAL @interface NavData : GPBMessage

/** 导航加密字符串 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *navEncryptStr;

@end

#pragma mark - IMServerListRequest

typedef GPB_ENUM(IMServerListRequest_FieldNumber) {
  IMServerListRequest_FieldNumber_AppId = 1,
  IMServerListRequest_FieldNumber_AppType = 2,
  IMServerListRequest_FieldNumber_ClientVersion = 3,
  IMServerListRequest_FieldNumber_Region = 4,
  IMServerListRequest_FieldNumber_DeviceType = 5,
  IMServerListRequest_FieldNumber_Timestamp = 6,
  IMServerListRequest_FieldNumber_Signature = 7,
  IMServerListRequest_FieldNumber_ClientIp = 8,
  IMServerListRequest_FieldNumber_SdkVersion = 9,
  IMServerListRequest_FieldNumber_Nonce = 10,
};

/**
 * IM服务器列表请求协议（客户端 → 导航服务）
 **/
GPB_FINAL @interface IMServerListRequest : GPBMessage

/** 【必填】邀请码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *appId;

/** app类型 0:公共打包 1:独立打包 */
@property(nonatomic, readwrite) IMServerListRequest_DataType appType;

/** 【必填】客户端版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientVersion;

/** 【必填】地区标识 (CN/US/EU/AP) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *region;

/** 【必填】设备类型 (ios/android/pc/web) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *deviceType;

/** 【必填】请求时间戳 */
@property(nonatomic, readwrite) int64_t timestamp;

/** 【必填】请求签名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *signature;

/** 【非必填】客户端IP地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clientIp;

/** 【非必填】SDK版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sdkVersion;

/** 【必填】随机字符串，防重放攻击 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *nonce;

@end

/**
 * Fetches the raw value of a @c IMServerListRequest's @c appType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t IMServerListRequest_AppType_RawValue(IMServerListRequest *message);
/**
 * Sets the raw value of an @c IMServerListRequest's @c appType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetIMServerListRequest_AppType_RawValue(IMServerListRequest *message, int32_t value);

#pragma mark - IMServerListResponse

typedef GPB_ENUM(IMServerListResponse_FieldNumber) {
  IMServerListResponse_FieldNumber_StatusCode = 1,
  IMServerListResponse_FieldNumber_Message = 2,
  IMServerListResponse_FieldNumber_ResponseBody = 3,
  IMServerListResponse_FieldNumber_ServerTimestamp = 4,
};

/**
 * IM服务器列表响应协议（导航服务 → 客户端）
 **/
GPB_FINAL @interface IMServerListResponse : GPBMessage

/** 【必填】状态码（使用6位错误码） */
@property(nonatomic, readwrite) int32_t statusCode;

/** 【必填】响应消息 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

/** 【必填】加密的响应体数据 */
@property(nonatomic, readwrite, copy, null_resettable) NSData *responseBody;

/** 【必填】服务器时间戳 */
@property(nonatomic, readwrite) int64_t serverTimestamp;

@end

#pragma mark - IMServerListResponseBody

typedef GPB_ENUM(IMServerListResponseBody_FieldNumber) {
  IMServerListResponseBody_FieldNumber_ImEndpointsArray = 1,
  IMServerListResponseBody_FieldNumber_Meta = 2,
  IMServerListResponseBody_FieldNumber_FallbackEndpoints = 3,
  IMServerListResponseBody_FieldNumber_CacheTtl = 4,
};

/**
 * IM服务器列表响应体（加密传输）
 **/
GPB_FINAL @interface IMServerListResponseBody : GPBMessage

/** 【必填】IM服务器列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<IMServerEndpoint*> *imEndpointsArray;
/** The number of items in @c imEndpointsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger imEndpointsArray_Count;

/** 【非必填】元数据信息 */
@property(nonatomic, readwrite, strong, null_resettable) NavigationMeta *meta;
/** Test to see if @c meta has been set. */
@property(nonatomic, readwrite) BOOL hasMeta;

/** 【非必填】兜底导航地址 */
@property(nonatomic, readwrite, strong, null_resettable) FallbackEndpoints *fallbackEndpoints;
/** Test to see if @c fallbackEndpoints has been set. */
@property(nonatomic, readwrite) BOOL hasFallbackEndpoints;

/** 【必填】缓存有效期(秒) */
@property(nonatomic, readwrite) int64_t cacheTtl;

@end

#pragma mark - IMServerEndpoint

typedef GPB_ENUM(IMServerEndpoint_FieldNumber) {
  IMServerEndpoint_FieldNumber_Ip = 1,
  IMServerEndpoint_FieldNumber_Port = 2,
  IMServerEndpoint_FieldNumber_Weight = 3,
  IMServerEndpoint_FieldNumber_Region = 4,
  IMServerEndpoint_FieldNumber_Status = 5,
  IMServerEndpoint_FieldNumber_Latency = 6,
  IMServerEndpoint_FieldNumber_ServerId = 7,
  IMServerEndpoint_FieldNumber_ClusterId = 8,
  IMServerEndpoint_FieldNumber_Load = 9,
  IMServerEndpoint_FieldNumber_ProtocolsArray = 10,
};

/**
 * IM服务器节点信息
 **/
GPB_FINAL @interface IMServerEndpoint : GPBMessage

/** 【必填】IP地址 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *ip;

/** 【必填】端口号 */
@property(nonatomic, readwrite) int32_t port;

/** 【必填】权重(1-100) */
@property(nonatomic, readwrite) int32_t weight;

/** 【非必填】所属地区 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *region;

/** 【必填】状态(ACTIVE/INACTIVE) */
@property(nonatomic, readwrite, copy, null_resettable) NSString *status;

/** 【非必填】延迟(ms) */
@property(nonatomic, readwrite) int64_t latency;

/** 【必填】服务器标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *serverId;

/** 【非必填】集群标识 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *clusterId;

/** 【非必填】当前负载(0-100) */
@property(nonatomic, readwrite) int32_t load;

/** 【非必填】支持的协议列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *protocolsArray;
/** The number of items in @c protocolsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger protocolsArray_Count;

@end

#pragma mark - NavigationMeta

typedef GPB_ENUM(NavigationMeta_FieldNumber) {
  NavigationMeta_FieldNumber_NavVersion = 1,
  NavigationMeta_FieldNumber_Config = 2,
  NavigationMeta_FieldNumber_NextUpdateTime = 3,
  NavigationMeta_FieldNumber_TraceId = 4,
};

/**
 * 导航元数据
 **/
GPB_FINAL @interface NavigationMeta : GPBMessage

/** 【必填】导航服务版本 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *navVersion;

/** 【非必填】客户端配置 */
@property(nonatomic, readwrite, strong, null_resettable) NavigationConfig *config;
/** Test to see if @c config has been set. */
@property(nonatomic, readwrite) BOOL hasConfig;

/** 【非必填】下次更新时间 */
@property(nonatomic, readwrite) int64_t nextUpdateTime;

/** 【非必填】请求追踪ID */
@property(nonatomic, readwrite, copy, null_resettable) NSString *traceId;

@end

#pragma mark - NavigationConfig

typedef GPB_ENUM(NavigationConfig_FieldNumber) {
  NavigationConfig_FieldNumber_ConnectTimeout = 1,
  NavigationConfig_FieldNumber_ReadTimeout = 2,
  NavigationConfig_FieldNumber_MaxRetryCount = 3,
  NavigationConfig_FieldNumber_RaceTimeout = 4,
  NavigationConfig_FieldNumber_CacheDuration = 5,
  NavigationConfig_FieldNumber_EnableNetworkDetect = 6,
  NavigationConfig_FieldNumber_SentryUrlsArray = 7,
  NavigationConfig_FieldNumber_LoganUrlsArray = 8,
};

/**
 * 客户端配置
 **/
GPB_FINAL @interface NavigationConfig : GPBMessage

/** 【非必填】连接超时(ms)，默认10000 */
@property(nonatomic, readwrite) int32_t connectTimeout;

/** 【非必填】读取超时(ms)，默认5000 */
@property(nonatomic, readwrite) int32_t readTimeout;

/** 【非必填】最大重试次数，默认3 */
@property(nonatomic, readwrite) int32_t maxRetryCount;

/** 【非必填】竞速超时(ms)，默认3000 */
@property(nonatomic, readwrite) int32_t raceTimeout;

/** 【非必填】缓存时长(秒)，默认3600 */
@property(nonatomic, readwrite) int32_t cacheDuration;

/** 【非必填】是否启用网络探测，默认true */
@property(nonatomic, readwrite) BOOL enableNetworkDetect;

/** 【非必填】Sentry服务地址列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *sentryUrlsArray;
/** The number of items in @c sentryUrlsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger sentryUrlsArray_Count;

/** 【非必填】Logan服务地址列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *loganUrlsArray;
/** The number of items in @c loganUrlsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger loganUrlsArray_Count;

@end

#pragma mark - FallbackEndpoints

typedef GPB_ENUM(FallbackEndpoints_FieldNumber) {
  FallbackEndpoints_FieldNumber_DomesticArray = 1,
  FallbackEndpoints_FieldNumber_OverseasArray = 2,
};

/**
 * 兜底导航地址
 **/
GPB_FINAL @interface FallbackEndpoints : GPBMessage

/** 【非必填】国内导航地址 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *domesticArray;
/** The number of items in @c domesticArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger domesticArray_Count;

/** 【非必填】海外导航地址 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *overseasArray;
/** The number of items in @c overseasArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger overseasArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
